SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `courses`;
DROP TABLE IF EXISTS `degrees`;
DROP TABLE IF EXISTS `departments`;
DROP TABLE IF EXISTS `major`;
DROP TABLE IF EXISTS `minor`;
DROP TABLE IF EXISTS `register`;
DROP TABLE IF EXISTS `students`;
SET FOREIGN_KEY_CHECKS = 1;